export const seedLearningItems = [
  {
    title: 'Democracy',
    type: 'concept',
    content: 'Democracy is a political system in which authority is derived from the people and exercised through accountable institutions.',
    explanation: 'The focus is not only elections, but legitimacy, accountability, and civic participation.',
    sourceText: 'Core civic learning topic for political literacy and institutional reasoning.',
    tags: ['democracy', 'civic institutions'],
    difficulty: 3,
    learningMode: 'active_recall',
  },
  {
    title: 'Leadership',
    type: 'principle',
    content: 'Leadership is the disciplined practice of aligning people, decisions, and standards under pressure.',
    explanation: 'It combines judgment, trust, accountability, and the ability to act through others.',
    sourceText: 'Internal leadership development note.',
    tags: ['leadership'],
    difficulty: 3,
    learningMode: 'deliberate_practice',
  },
  {
    title: 'Negotiation',
    type: 'framework',
    content: 'Strong negotiation balances leverage, interests, alternatives, and relationship preservation.',
    explanation: 'The goal is not only to win a point, but to produce a durable and advantageous agreement.',
    sourceText: 'Negotiation framework for operators and leaders.',
    tags: ['negotiation', 'argumentation'],
    difficulty: 4,
    learningMode: 'interleaving',
  },
  {
    title: 'Public speaking',
    type: 'concept',
    content: 'Public speaking is the structured delivery of ideas for clarity, persuasion, and action.',
    explanation: 'It relies on thesis control, pacing, structure, and rhetorical judgment.',
    sourceText: 'Communication training topic for speech practice.',
    tags: ['public speaking', 'communication'],
    difficulty: 3,
    learningMode: 'active_recall',
  },
  {
    title: 'Product strategy',
    type: 'framework',
    content: 'Product strategy determines where to compete, what to prioritize, and how to sequence product decisions over time.',
    explanation: 'It connects user value, market positioning, constraints, and execution capacity.',
    sourceText: 'Product and business strategy primer.',
    tags: ['product strategy', 'business'],
    difficulty: 4,
    learningMode: 'interleaving',
  },
  {
    title: 'Systems thinking',
    type: 'concept',
    content: 'Systems thinking analyzes how parts interact, how feedback loops behave, and how second-order effects emerge.',
    explanation: 'It prevents naive linear reasoning in complex environments.',
    sourceText: 'Core reasoning skill for policy, business, and operations.',
    tags: ['systems thinking', 'reasoning'],
    difficulty: 4,
    learningMode: 'spaced_repetition',
  },
  {
    title: 'Ethics',
    type: 'principle',
    content: 'Ethics concerns the standards by which choices are judged as right, responsible, and defensible.',
    explanation: 'In practice, ethics requires balancing principles, duties, consequences, and institutional trust.',
    sourceText: 'Ethical reasoning foundation.',
    tags: ['ethics'],
    difficulty: 4,
    learningMode: 'deliberate_practice',
  },
  {
    title: 'Economics',
    type: 'concept',
    content: 'Economics studies scarcity, incentives, tradeoffs, and allocation across individuals and institutions.',
    explanation: 'It helps interpret policy, markets, resource constraints, and strategic behavior.',
    sourceText: 'Economic literacy concept.',
    tags: ['economics'],
    difficulty: 3,
    learningMode: 'spaced_repetition',
  },
  {
    title: 'Civic institutions',
    type: 'concept',
    content: 'Civic institutions are the formal and informal structures through which public life is governed and coordinated.',
    explanation: 'Understanding them is essential for legitimacy, reform, and public accountability.',
    sourceText: 'Institutional literacy topic.',
    tags: ['civic institutions', 'democracy'],
    difficulty: 3,
    learningMode: 'active_recall',
  },
  {
    title: 'Argumentation',
    type: 'framework',
    content: 'Argumentation is the disciplined construction of claims, evidence, warrants, counterarguments, and conclusions.',
    explanation: 'It improves both persuasion and analytical rigor.',
    sourceText: 'Rhetoric and reasoning framework.',
    tags: ['argumentation', 'communication'],
    difficulty: 3,
    learningMode: 'interleaving',
  },
] as const;

export const seedDecisionScenarios = [
  {
    title: 'Municipal budget crisis',
    summary: 'A city administration must cut spending without breaking core services or public trust.',
    context: 'Revenue has fallen sharply while public pressure is rising. A politically popular program is no longer financially sustainable.',
    prompt: 'What do you cut, what do you protect, and how do you justify the sequence publicly?',
    constraints: ['Immediate fiscal gap', 'Election cycle pressure', 'Legal obligations remain fixed'],
    stakeholders: ['Mayor', 'Citizens', 'Municipal staff', 'Local media'],
    availableOptions: ['Across-the-board cuts', 'Targeted cuts with reform', 'Short-term borrowing and phased adjustment'],
    hiddenRisks: ['Short-term patch may worsen long-term solvency', 'Visible cuts can trigger legitimacy backlash'],
    evaluationRubric: ['Clarity of tradeoffs', 'Civic legitimacy', 'Practical sequencing'],
    stakes: ['Budget stability', 'Public trust', 'Service continuity'],
    tags: ['civic', 'economics'],
    difficulty: 4,
  },
  {
    title: 'Product launch under instability',
    summary: 'A major launch is promised publicly, but infrastructure reliability is deteriorating.',
    context: 'Sales wants the launch date protected while engineering warns of failure risk.',
    prompt: 'Do you launch on time, narrow scope, or delay? Explain the tradeoff as an executive.',
    constraints: ['Public commitment already made', 'Limited engineering capacity', 'Competitive pressure is rising'],
    stakeholders: ['Customers', 'Engineering', 'Sales', 'Executive team'],
    availableOptions: ['Launch as planned', 'Reduce scope', 'Delay'],
    hiddenRisks: ['Scope cuts may still fail operationally', 'Delay may erode market confidence'],
    evaluationRubric: ['Strategic thinking', 'Risk awareness', 'Actionability'],
    stakes: ['Revenue', 'Reputation', 'Operational resilience'],
    tags: ['product strategy', 'systems thinking'],
    difficulty: 4,
  },
] as const;

export const seedProfileMemory = {
  strengths: ['argumentation', 'leadership'],
  weaknesses: ['economics', 'systems thinking'],
  preferredModes: ['active_recall', 'interleaving'],
  recurringErrors: [
    'Moves too quickly from conclusion to recommendation without surfacing tradeoffs.',
    'Needs stronger numerical or structural backing when discussing economics.',
  ],
  speechPatterns: [
    'Strong on conviction, weaker on compression and concision.',
    'Needs cleaner openings before elaboration.',
  ],
  decisionPatterns: [
    'Usually action-oriented, but can underweight second-order risk.',
    'Shows strong ownership when stakes are interpersonal.',
  ],
  conceptMastery: {
    leadership: 5,
    argumentation: 4,
    economics: 2,
    'systems thinking': 2,
  },
  recommendations: [
    'Do one economics review and one systems thinking scenario next.',
    'Practice a 90-second public explanation with tighter structure.',
  ],
  recentActivity: [
    'Reviewed leadership frameworks.',
    'Completed one decision scenario on product strategy.',
  ],
  aiSummary: null,
} as const;
